### ISSUE TITLE
General molecular picture on the front page

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/Series-3-Phenothiazines#3]
I'll ask around as to whether this series has been evaluated vs eumycetoma. The preliminary data you've listed on the main repo page ("Code", above - in the readme) @MFernflower is very good. Could you add one molecular structure pic to make clear the nature of the series we're talking about. A structure can help to get medchemists' minds in the right gear.

**Comment by MFernflower** [comment]
And done!
