### ISSUE TITLE
Sourcing phenothiazines from commercial sources?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-3-Phenothiazines#7]
Since all of the labs in the MYOS program are busy working on other projects - I will float the idea of buying one or two of these s3 compounds (N-substituted-phenothiazines) from a commercial source just to see if they are effective against mycetoma/are worth following up on. 

https://www.oakwoodchemical.com/ProductsList.aspx?CategoryID=-2&txtSearch=166278&ExtHyperLink=1 - 25mg bottle is 211 USD (seems to be only supplier????) - N-phenethyl-phenothiazine

https://www.ambeed.com/products/15375-48-1.html 100mg bottle is 122 USD - N-propyl-phenothiazine

https://www.matrixscientific.com/059688.html Fenethazine monohydrochloride 1/2 gram bottle is 171 USD

https://www.tcichemicals.com/US/en/p/M3068 - Some organic semiconductor material called MEEPT - 10 grams of liquid product 278 dollars -  Looks like it could be worthy to test

For such simple compounds that seems like a lot of money but if a member of @OpenSourceMycetoma/corecontrib has some university budget perhaps it could be done? 

Callback to issue #2 where I mentioned a company called Toronto research chemicals

**Comment by MFernflower** [comment]
@bebi78 is one or two of these within reach of you allotted budget?

**Comment by MFernflower** [comment]
Fenethazine monohydrochloride and N-phenethyl-phenothiazine are the two I think would prove the most interesting

**Comment by MFernflower** [comment]
Issue #1  talked about this a long time ago (just as a cross reference)

**Comment by MFernflower** [comment]
Spreadsheet for upcomming meeting is here https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/blob/master/PHENOTHIAZINE_WISHLIST.xlsx

**Comment by bebi78** [comment]
@MFernflower Sorry, I don't have money left at the moment. So we might either ask providers for free samples of ca. 2-3 mg, or students of @JuliaSarju might prepare them.

**Comment by JuliaSarju** [comment]
We think the first 2 should be ok to make. Happy to give it ago once term
starts :)
Dr Julia Sarju FHEA , [image: A button with "Hear my name" text for name
playback in email signature] <https://www.name-coach.com/julia-sarju>
She/Her
Lecturer in Chemistry, Year One Leader, and Chemistry Disability Contact
The University of York

*UG + PG Chemistry Students:* Do you have experiences of inequalities in
chemistry education that you want to share with chemistry instructors? Are
there actions you would like chemistry departments to take? Add your voice
and take part in this RSC Diversity and Inclusion project: Listening to
Inequalities in Chemistry Education
<https://docs.google.com/forms/d/e/1FAIpQLSfF-KSH-VXQOb55kLV_URwZkZVHB32QVM5TdapgSmEtJ3nTWQ/viewform?usp=sf_link>

Join the Student Disability Forum Mailing List
<https://docs.google.com/forms/d/e/1FAIpQLSejLDEYk84XxYXmFQmWphP0At3d0rjbIw_xrgVwS9hOAK7zRw/viewform>

**Comment by MFernflower** [comment]
Sounds good

**Comment by MFernflower** [comment]
@bebi78 to maybe try to reach out to NEU to see if this can move forward

**Comment by MFernflower** [comment]
Closing as between the compounds from NEU and the ones being made at York we now have a good jump start to this project
