### ISSUE TITLE
Novel synthesis route to N-alkyl-phenothiazines

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-3-Phenothiazines#9]
https://pubs.acs.org/doi/10.1021/acs.orglett.5b03058

May be of interest to @JuliaSarju and her team at York

**Comment by JuliaSarju** [comment]
Thank you!

**Comment by MFernflower** [comment]
If you can @JuliaSarju <https://github.com/JuliaSarju> can you post
structures of what your team is going to make on the other issue - I think
a mix of both big and small side chains should be good!

**Comment by MFernflower** [comment]
@JuliaSarju gonna close this since you likely already downloaded the paper - Also I was wondering if it would be possible for you to give an update on the progress of the phenothiazine project?
